version: "2"
services:

  n1:
    image: nginxdemos/hello
    restart: always
    labels:
      cz.drake.proxy.domain: a.device.farm
      cz.drake.proxy.port: "80"

  n2:
    image: nginxdemos/hello
    restart: always
    labels:
      cz.drake.proxy.domain: a.ovh1.device.farm
      cz.drake.proxy.port: "80"
